plugins {
    id 'java'
    id 'application'
}

group = 'genius'
version = '1.0-SNAPSHOT'

sourceCompatibility = '21'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.commons:commons-lang3:3.12.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

application {
    mainClass = 'genius.Main'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes(
                'Main-Class': 'genius.Main'
        )
    }
}
